/*
 * @Author: truxcoder
 * @Date: 2022-03-03 20:00:44
 * @LastEditTime: 2022-03-31 16:58:11
 * @LastEditors: truxcoder
 * @Description:
 */
export const iconList = [
  { value: 'el-icon-platform-eleme' },
  { value: 'el-icon-eleme' },
  { value: 'el-icon-delete-solid' },
  { value: 'el-icon-delete' },
  { value: 'el-icon-s-tools' },
  { value: 'el-icon-setting' },
  { value: 'el-icon-user-solid' },
  { value: 'el-icon-user' },
  { value: 'el-icon-phone' },
  { value: 'el-icon-phone-outline' },
  { value: 'el-icon-more' },
  { value: 'el-icon-more-outline' },
  { value: 'el-icon-star-on' },
  { value: 'el-icon-star-off' },
  { value: 'el-icon-s-goods' },
  { value: 'el-icon-goods' },
  { value: 'el-icon-warning' },
  { value: 'el-icon-warning-outline' },
  { value: 'el-icon-question' },
  { value: 'el-icon-info' },
  { value: 'el-icon-remove' },
  { value: 'el-icon-circle-plus' },
  { value: 'el-icon-success' },
  { value: 'el-icon-error' },
  { value: 'el-icon-zoom-in' },
  { value: 'el-icon-zoom-out' },
  { value: 'el-icon-remove-outline' },
  { value: 'el-icon-circle-plus-outline' },
  { value: 'el-icon-circle-check' },
  { value: 'el-icon-circle-close' },
  { value: 'el-icon-s-help' },
  { value: 'el-icon-help' },
  { value: 'el-icon-minus' },
  { value: 'el-icon-plus' },
  { value: 'el-icon-check' },
  { value: 'el-icon-close' },
  { value: 'el-icon-picture' },
  { value: 'el-icon-picture-outline' },
  { value: 'el-icon-picture-outline-round' },
  { value: 'el-icon-upload' },
  { value: 'el-icon-upload2' },
  { value: 'el-icon-download' },
  { value: 'el-icon-camera-solid' },
  { value: 'el-icon-camera' },
  { value: 'el-icon-video-camera-solid' },
  { value: 'el-icon-video-camera' },
  { value: 'el-icon-message-solid' },
  { value: 'el-icon-bell' },
  { value: 'el-icon-s-cooperation' },
  { value: 'el-icon-s-order' },
  { value: 'el-icon-s-platform' },
  { value: 'el-icon-s-fold' },
  { value: 'el-icon-s-unfold' },
  { value: 'el-icon-s-operation' },
  { value: 'el-icon-s-promotion' },
  { value: 'el-icon-s-home' },
  { value: 'el-icon-s-release' },
  { value: 'el-icon-s-ticket' },
  { value: 'el-icon-s-management' },
  { value: 'el-icon-s-open' },
  { value: 'el-icon-s-shop' },
  { value: 'el-icon-s-marketing' },
  { value: 'el-icon-s-flag' },
  { value: 'el-icon-s-comment' },
  { value: 'el-icon-s-finance' },
  { value: 'el-icon-s-claim' },
  { value: 'el-icon-s-custom' },
  { value: 'el-icon-s-opportunity' },
  { value: 'el-icon-s-data' },
  { value: 'el-icon-s-check' },
  { value: 'el-icon-s-grid' },
  { value: 'el-icon-menu' },
  { value: 'el-icon-share' },
  { value: 'el-icon-d-caret' },
  { value: 'el-icon-caret-left' },
  { value: 'el-icon-caret-right' },
  { value: 'el-icon-caret-bottom' },
  { value: 'el-icon-caret-top' },
  { value: 'el-icon-bottom-left' },
  { value: 'el-icon-bottom-right' },
  { value: 'el-icon-back' },
  { value: 'el-icon-right' },
  { value: 'el-icon-bottom' },
  { value: 'el-icon-top' },
  { value: 'el-icon-top-left' },
  { value: 'el-icon-top-right' },
  { value: 'el-icon-arrow-left' },
  { value: 'el-icon-arrow-right' },
  { value: 'el-icon-arrow-down' },
  { value: 'el-icon-arrow-up' },
  { value: 'el-icon-d-arrow-left' },
  { value: 'el-icon-d-arrow-right' },
  { value: 'el-icon-video-pause' },
  { value: 'el-icon-video-play' },
  { value: 'el-icon-refresh' },
  { value: 'el-icon-refresh-right' },
  { value: 'el-icon-refresh-left' },
  { value: 'el-icon-finished' },
  { value: 'el-icon-sort' },
  { value: 'el-icon-sort-up' },
  { value: 'el-icon-sort-down' },
  { value: 'el-icon-rank' },
  { value: 'el-icon-loading' },
  { value: 'el-icon-view' },
  { value: 'el-icon-c-scale-to-original' },
  { value: 'el-icon-date' },
  { value: 'el-icon-edit' },
  { value: 'el-icon-edit-outline' },
  { value: 'el-icon-folder' },
  { value: 'el-icon-folder-opened' },
  { value: 'el-icon-folder-add' },
  { value: 'el-icon-folder-remove' },
  { value: 'el-icon-folder-delete' },
  { value: 'el-icon-folder-checked' },
  { value: 'el-icon-tickets' },
  { value: 'el-icon-document-remove' },
  { value: 'el-icon-document-delete' },
  { value: 'el-icon-document-copy' },
  { value: 'el-icon-document-checked' },
  { value: 'el-icon-document' },
  { value: 'el-icon-document-add' },
  { value: 'el-icon-printer' },
  { value: 'el-icon-paperclip' },
  { value: 'el-icon-takeaway-box' },
  { value: 'el-icon-search' },
  { value: 'el-icon-monitor' },
  { value: 'el-icon-attract' },
  { value: 'el-icon-mobile' },
  { value: 'el-icon-scissors' },
  { value: 'el-icon-umbrella' },
  { value: 'el-icon-headset' },
  { value: 'el-icon-brush' },
  { value: 'el-icon-mouse' },
  { value: 'el-icon-coordinate' },
  { value: 'el-icon-magic-stick' },
  { value: 'el-icon-reading' },
  { value: 'el-icon-data-line' },
  { value: 'el-icon-data-board' },
  { value: 'el-icon-pie-chart' },
  { value: 'el-icon-data-analysis' },
  { value: 'el-icon-collection-tag' },
  { value: 'el-icon-film' },
  { value: 'el-icon-suitcase' },
  { value: 'el-icon-suitcase-1' },
  { value: 'el-icon-receiving' },
  { value: 'el-icon-collection' },
  { value: 'el-icon-files' },
  { value: 'el-icon-notebook-1' },
  { value: 'el-icon-notebook-2' },
  { value: 'el-icon-toilet-paper' },
  { value: 'el-icon-office-building' },
  { value: 'el-icon-school' },
  { value: 'el-icon-table-lamp' },
  { value: 'el-icon-house' },
  { value: 'el-icon-no-smoking' },
  { value: 'el-icon-smoking' },
  { value: 'el-icon-shopping-cart-full' },
  { value: 'el-icon-shopping-cart-1' },
  { value: 'el-icon-shopping-cart-2' },
  { value: 'el-icon-shopping-bag-1' },
  { value: 'el-icon-shopping-bag-2' },
  { value: 'el-icon-sold-out' },
  { value: 'el-icon-sell' },
  { value: 'el-icon-present' },
  { value: 'el-icon-box' },
  { value: 'el-icon-bank-card' },
  { value: 'el-icon-money' },
  { value: 'el-icon-coin' },
  { value: 'el-icon-wallet' },
  { value: 'el-icon-discount' },
  { value: 'el-icon-price-tag' },
  { value: 'el-icon-news' },
  { value: 'el-icon-guide' },
  { value: 'el-icon-male' },
  { value: 'el-icon-female' },
  { value: 'el-icon-thumb' },
  { value: 'el-icon-cpu' },
  { value: 'el-icon-link' },
  { value: 'el-icon-connection' },
  { value: 'el-icon-open' },
  { value: 'el-icon-turn-off' },
  { value: 'el-icon-set-up' },
  { value: 'el-icon-chat-round' },
  { value: 'el-icon-chat-line-round' },
  { value: 'el-icon-chat-square' },
  { value: 'el-icon-chat-dot-round' },
  { value: 'el-icon-chat-dot-square' },
  { value: 'el-icon-chat-line-square' },
  { value: 'el-icon-message' },
  { value: 'el-icon-postcard' },
  { value: 'el-icon-position' },
  { value: 'el-icon-turn-off-microphone' },
  { value: 'el-icon-microphone' },
  { value: 'el-icon-close-notification' },
  { value: 'el-icon-bangzhu' },
  { value: 'el-icon-time' },
  { value: 'el-icon-odometer' },
  { value: 'el-icon-crop' },
  { value: 'el-icon-aim' },
  { value: 'el-icon-switch-button' },
  { value: 'el-icon-full-screen' },
  { value: 'el-icon-copy-document' },
  { value: 'el-icon-mic' },
  { value: 'el-icon-stopwatch' },
  { value: 'el-icon-medal-1' },
  { value: 'el-icon-medal' },
  { value: 'el-icon-trophy' },
  { value: 'el-icon-trophy-1' },
  { value: 'el-icon-first-aid-kit' },
  { value: 'el-icon-discover' },
  { value: 'el-icon-place' },
  { value: 'el-icon-location' },
  { value: 'el-icon-location-outline' },
  { value: 'el-icon-location-information' },
  { value: 'el-icon-add-location' },
  { value: 'el-icon-delete-location' },
  { value: 'el-icon-map-location' },
  { value: 'el-icon-alarm-clock' },
  { value: 'el-icon-timer' },
  { value: 'el-icon-watch-1' },
  { value: 'el-icon-watch' },
  { value: 'el-icon-lock' },
  { value: 'el-icon-unlock' },
  { value: 'el-icon-key' },
  { value: 'el-icon-service' },
  { value: 'el-icon-mobile-phone' },
  { value: 'el-icon-bicycle' },
  { value: 'el-icon-truck' },
  { value: 'el-icon-ship' },
  { value: 'el-icon-basketball' },
  { value: 'el-icon-football' },
  { value: 'el-icon-soccer' },
  { value: 'el-icon-baseball' },
  { value: 'el-icon-wind-power' },
  { value: 'el-icon-light-rain' },
  { value: 'el-icon-lightning' },
  { value: 'el-icon-heavy-rain' },
  { value: 'el-icon-sunrise' },
  { value: 'el-icon-sunrise-1' },
  { value: 'el-icon-sunset' },
  { value: 'el-icon-sunny' },
  { value: 'el-icon-cloudy' },
  { value: 'el-icon-partly-cloudy' },
  { value: 'el-icon-cloudy-and-sunny' },
  { value: 'el-icon-moon' },
  { value: 'el-icon-moon-night' },
  { value: 'el-icon-dish' },
  { value: 'el-icon-dish-1' },
  { value: 'el-icon-food' },
  { value: 'el-icon-chicken' },
  { value: 'el-icon-fork-spoon' },
  { value: 'el-icon-knife-fork' },
  { value: 'el-icon-burger' },
  { value: 'el-icon-tableware' },
  { value: 'el-icon-sugar' },
  { value: 'el-icon-dessert' },
  { value: 'el-icon-ice-cream' },
  { value: 'el-icon-hot-water' },
  { value: 'el-icon-water-cup' },
  { value: 'el-icon-coffee-cup' },
  { value: 'el-icon-cold-drink' },
  { value: 'el-icon-goblet' },
  { value: 'el-icon-goblet-full' },
  { value: 'el-icon-goblet-square' },
  { value: 'el-icon-goblet-square-full' },
  { value: 'el-icon-refrigerator' },
  { value: 'el-icon-grape' },
  { value: 'el-icon-watermelon' },
  { value: 'el-icon-cherry' },
  { value: 'el-icon-apple' },
  { value: 'el-icon-pear' },
  { value: 'el-icon-orange' },
  { value: 'el-icon-coffee' },
  { value: 'el-icon-ice-tea' },
  { value: 'el-icon-ice-drink' },
  { value: 'el-icon-milk-tea' },
  { value: 'el-icon-potato-strips' },
  { value: 'el-icon-lollipop' },
  { value: 'el-icon-ice-cream-square' },
  { value: 'el-icon-ice-cream-round' },
  { value: 'el-icon-scjd-alert iconfont' },
  { value: 'el-icon-scjd-alert-fill iconfont' },
  { value: 'el-icon-scjd-all iconfont' },
  { value: 'el-icon-scjd-all-fill iconfont' },
  { value: 'el-icon-scjd-apartment iconfont' },
  { value: 'el-icon-scjd-api iconfont' },
  { value: 'el-icon-scjd-api-fill iconfont' },
  { value: 'el-icon-scjd-arrawsalt iconfont' },
  { value: 'el-icon-scjd-arrows-down-circle iconfont' },
  { value: 'el-icon-scjd-arrows-down-circle-fill iconfont' },
  { value: 'el-icon-scjd-arrows-download iconfont' },
  { value: 'el-icon-scjd-arrows-download1 iconfont' },
  { value: 'el-icon-scjd-arrows-enter iconfont' },
  { value: 'el-icon-scjd-arrows-export iconfont' },
  { value: 'el-icon-scjd-arrows-fullscreen iconfont' },
  { value: 'el-icon-scjd-arrows-fullscreen-exit iconfont' },
  { value: 'el-icon-scjd-arrows-Import iconfont' },
  { value: 'el-icon-scjd-arrows-interation iconfont' },
  { value: 'el-icon-scjd-arrows-left-circle iconfont' },
  { value: 'el-icon-scjd-arrows-left-circle-fill iconfont' },
  { value: 'el-icon-scjd-arrows-link1 iconfont' },
  { value: 'el-icon-scjd-arrows-login iconfont' },
  { value: 'el-icon-scjd-arrows-logout iconfont' },
  { value: 'el-icon-scjd-arrows-redo iconfont' },
  { value: 'el-icon-scjd-arrows-reloadtime iconfont' },
  { value: 'el-icon-scjd-arrows-retweet iconfont' },
  { value: 'el-icon-scjd-arrows-right-circle iconfont' },
  { value: 'el-icon-scjd-arrows-right-circle-fill iconfont' },
  { value: 'el-icon-scjd-arrows-rollback iconfont' },
  { value: 'el-icon-scjd-arrows-select iconfont' },
  { value: 'el-icon-scjd-arrows-shrink iconfont' },
  { value: 'el-icon-scjd-arrows-swap iconfont' },
  { value: 'el-icon-scjd-arrows-swap-left iconfont' },
  { value: 'el-icon-scjd-arrows-swap-right iconfont' },
  { value: 'el-icon-scjd-arrows-undo iconfont' },
  { value: 'el-icon-scjd-arrows-up-circle iconfont' },
  { value: 'el-icon-scjd-arrows-up-circle-fill iconfont' },
  { value: 'el-icon-scjd-arrows-upload iconfont' },
  { value: 'el-icon-scjd-arrows-upload1 iconfont' },
  { value: 'el-icon-scjd-arrows-vertical-align-middl iconfont' },
  { value: 'el-icon-scjd-audio-fill iconfont' },
  { value: 'el-icon-scjd-audit iconfont' },
  { value: 'el-icon-scjd-aviation iconfont' },
  { value: 'el-icon-scjd-balance iconfont' },
  { value: 'el-icon-scjd-bank iconfont' },
  { value: 'el-icon-scjd-batchfolding iconfont' },
  { value: 'el-icon-scjd-batchfolding-fill iconfont' },
  { value: 'el-icon-scjd-bg-colors iconfont' },
  { value: 'el-icon-scjd-block iconfont' },
  { value: 'el-icon-scjd-book iconfont' },
  { value: 'el-icon-scjd-book1 iconfont' },
  { value: 'el-icon-scjd-book1-fill iconfont' },
  { value: 'el-icon-scjd-book-fill iconfont' },
  { value: 'el-icon-scjd-border iconfont' },
  { value: 'el-icon-scjd-box iconfont' },
  { value: 'el-icon-scjd-box-plot iconfont' },
  { value: 'el-icon-scjd-box-plot-fill iconfont' },
  { value: 'el-icon-scjd-branches iconfont' },
  { value: 'el-icon-scjd-bug iconfont' },
  { value: 'el-icon-scjd-bug-fill iconfont' },
  { value: 'el-icon-scjd-build iconfont' },
  { value: 'el-icon-scjd-build-fill iconfont' },
  { value: 'el-icon-scjd-calculator iconfont' },
  { value: 'el-icon-scjd-calendar iconfont' },
  { value: 'el-icon-scjd-calendar-check iconfont' },
  { value: 'el-icon-scjd-calendar-check-fill iconfont' },
  { value: 'el-icon-scjd-calendar-fill iconfont' },
  { value: 'el-icon-scjd-car iconfont' },
  { value: 'el-icon-scjd-car-fill iconfont' },
  { value: 'el-icon-scjd-cart-add iconfont' },
  { value: 'el-icon-scjd-cart-full iconfont' },
  { value: 'el-icon-scjd-cart-search iconfont' },
  { value: 'el-icon-scjd-cecurity-protection iconfont' },
  { value: 'el-icon-scjd-chart-area iconfont' },
  { value: 'el-icon-scjd-chart-bar iconfont' },
  { value: 'el-icon-scjd-chart-line iconfont' },
  { value: 'el-icon-scjd-chart-pointmap iconfont' },
  { value: 'el-icon-scjd-chart-radar iconfont' },
  { value: 'el-icon-scjd-chemistry iconfont' },
  { value: 'el-icon-scjd-circle-aim iconfont' },
  { value: 'el-icon-scjd-circle-ball iconfont' },
  { value: 'el-icon-scjd-circle-bulb iconfont' },
  { value: 'el-icon-scjd-circle-compass iconfont' },
  { value: 'el-icon-scjd-circle-compass-fill iconfont' },
  { value: 'el-icon-scjd-circle-daytimemode-fill iconfont' },
  { value: 'el-icon-scjd-circle-earth iconfont' },
  { value: 'el-icon-scjd-circle-field-time iconfont' },
  { value: 'el-icon-scjd-circle-forbidden iconfont' },
  { value: 'el-icon-scjd-circle-forbidden-fill iconfont' },
  { value: 'el-icon-scjd-circle-frown iconfont' },
  { value: 'el-icon-scjd-circle-help iconfont' },
  { value: 'el-icon-scjd-circle-info-circle iconfont' },
  { value: 'el-icon-scjd-circle-info-circle-fill iconfont' },
  { value: 'el-icon-scjd-circle-international iconfont' },
  { value: 'el-icon-scjd-circle-issuesclose iconfont' },
  { value: 'el-icon-scjd-circle-meh iconfont' },
  { value: 'el-icon-scjd-circle-nightmode iconfont' },
  { value: 'el-icon-scjd-circle-nightmode-fill iconfont' },
  { value: 'el-icon-scjd-circle-record iconfont' },
  { value: 'el-icon-scjd-circle-server-fault iconfont' },
  { value: 'el-icon-scjd-circle-smile iconfont' },
  { value: 'el-icon-scjd-circle-time iconfont' },
  { value: 'el-icon-scjd-circle-time-fill iconfont' },
  { value: 'el-icon-scjd-circle-trademark iconfont' },
  { value: 'el-icon-scjd-circle-trademark-fill iconfont' },
  { value: 'el-icon-scjd-clear iconfont' },
  { value: 'el-icon-scjd-cloud-download iconfont' },
  { value: 'el-icon-scjd-cloud-server iconfont' },
  { value: 'el-icon-scjd-cloud-sync iconfont' },
  { value: 'el-icon-scjd-cloud-upload iconfont' },
  { value: 'el-icon-scjd-cluster iconfont' },
  { value: 'el-icon-scjd-code iconfont' },
  { value: 'el-icon-scjd-code-bar iconfont' },
  { value: 'el-icon-scjd-codelibrary iconfont' },
  { value: 'el-icon-scjd-code-qr iconfont' },
  { value: 'el-icon-scjd-comment iconfont' },
  { value: 'el-icon-scjd-component iconfont' },
  { value: 'el-icon-scjd-compress iconfont' },
  { value: 'el-icon-scjd-contacts iconfont' },
  { value: 'el-icon-scjd-contacts-fill iconfont' },
  { value: 'el-icon-scjd-container iconfont' },
  { value: 'el-icon-scjd-container-fill iconfont' },
  { value: 'el-icon-scjd-control iconfont' },
  { value: 'el-icon-scjd-control-fill iconfont' },
  { value: 'el-icon-scjd-credit-card iconfont' },
  { value: 'el-icon-scjd-creditcard-fill iconfont' },
  { value: 'el-icon-scjd-crown iconfont' },
  { value: 'el-icon-scjd-crown-fill iconfont' },
  { value: 'el-icon-scjd-currency iconfont' },
  { value: 'el-icon-scjd-currency-account-book iconfont' },
  { value: 'el-icon-scjd-currency-accountbook-fill iconfont' },
  { value: 'el-icon-scjd-currency-dollar iconfont' },
  { value: 'el-icon-scjd-currency-Dollar1 iconfont' },
  { value: 'el-icon-scjd-currency-Dollar-fill iconfont' },
  { value: 'el-icon-scjd-currency-EURO iconfont' },
  { value: 'el-icon-scjd-currency-EURO-fill iconfont' },
  { value: 'el-icon-scjd-currency-jewelry iconfont' },
  { value: 'el-icon-scjd-currency-moneycollect iconfont' },
  { value: 'el-icon-scjd-currency-moneycollect-fill iconfont' },
  { value: 'el-icon-scjd-currency-Pound iconfont' },
  { value: 'el-icon-scjd-currency-Pound-fill iconfont' },
  { value: 'el-icon-scjd-currency-property iconfont' },
  { value: 'el-icon-scjd-currency-property-fill iconfont' },
  { value: 'el-icon-scjd-currency-redenvelope iconfont' },
  { value: 'el-icon-scjd-currency-redenvelope-fill iconfont' },
  { value: 'el-icon-scjd-currency-red-packet iconfont' },
  { value: 'el-icon-scjd-currency-rmb iconfont' },
  { value: 'el-icon-scjd-currency-transaction iconfont' },
  { value: 'el-icon-scjd-currency-wallet iconfont' },
  { value: 'el-icon-scjd-currency-wallet-fill iconfont' },
  { value: 'el-icon-scjd-currency-YUAN iconfont' },
  { value: 'el-icon-scjd-currency-YUAN-fill iconfont' },
  { value: 'el-icon-scjd-dashboard iconfont' },
  { value: 'el-icon-scjd-dashboard-fill iconfont' },
  { value: 'el-icon-scjd-database iconfont' },
  { value: 'el-icon-scjd-database-fill iconfont' },
  { value: 'el-icon-scjd-deployment-unit iconfont' },
  { value: 'el-icon-scjd-desktop iconfont' },
  { value: 'el-icon-scjd-detail iconfont' },
  { value: 'el-icon-scjd-detail-fill iconfont' },
  { value: 'el-icon-scjd-diff iconfont' },
  { value: 'el-icon-scjd-diff-fill iconfont' },
  { value: 'el-icon-scjd-disconnect iconfont' },
  { value: 'el-icon-scjd-drop-box iconfont' },
  { value: 'el-icon-scjd-edit iconfont' },
  { value: 'el-icon-scjd-edit-fill iconfont' },
  { value: 'el-icon-scjd-electronics iconfont' },
  { value: 'el-icon-scjd-emblem-China1 iconfont' },
  { value: 'el-icon-scjd-emblem-party1 iconfont' },
  { value: 'el-icon-scjd-emblem-party-fill iconfont' },
  { value: 'el-icon-scjd-emblem-police iconfont' },
  { value: 'el-icon-scjd-emblem-police1 iconfont' },
  { value: 'el-icon-scjd-emblem-police2 iconfont' },
  { value: 'el-icon-scjd-emblem-police4 iconfont' },
  { value: 'el-icon-scjd-eraser iconfont' },
  { value: 'el-icon-scjd-error iconfont' },
  { value: 'el-icon-scjd-error-fill iconfont' },
  { value: 'el-icon-scjd-experiment iconfont' },
  { value: 'el-icon-scjd-eye iconfont' },
  { value: 'el-icon-scjd-eye-close iconfont' },
  { value: 'el-icon-scjd-eyeclose-fill iconfont' },
  { value: 'el-icon-scjd-eye-fill iconfont' },
  { value: 'el-icon-scjd-file iconfont' },
  { value: 'el-icon-scjd-file-bmp iconfont' },
  { value: 'el-icon-scjd-file-cad iconfont' },
  { value: 'el-icon-scjd-file-copy iconfont' },
  { value: 'el-icon-scjd-file-doc iconfont' },
  { value: 'el-icon-scjd-filedone iconfont' },
  { value: 'el-icon-scjd-file-exception iconfont' },
  { value: 'el-icon-scjd-file-exclamation iconfont' },
  { value: 'el-icon-scjd-file-exl iconfont' },
  { value: 'el-icon-scjd-file-gif iconfont' },
  { value: 'el-icon-scjd-file-image iconfont' },
  { value: 'el-icon-scjd-file-jpeg iconfont' },
  { value: 'el-icon-scjd-file-markdown iconfont' },
  { value: 'el-icon-scjd-file-pdf iconfont' },
  { value: 'el-icon-scjd-file-png iconfont' },
  { value: 'el-icon-scjd-file-ppt iconfont' },
  { value: 'el-icon-scjd-fileprotect iconfont' },
  { value: 'el-icon-scjd-filesearch iconfont' },
  { value: 'el-icon-scjd-filesync iconfont' },
  { value: 'el-icon-scjd-file-tif iconfont' },
  { value: 'el-icon-scjd-file-txt iconfont' },
  { value: 'el-icon-scjd-file-unknown iconfont' },
  { value: 'el-icon-scjd-file-word iconfont' },
  { value: 'el-icon-scjd-file-xlsx iconfont' },
  { value: 'el-icon-scjd-file-zip iconfont' },
  { value: 'el-icon-scjd-filter iconfont' },
  { value: 'el-icon-scjd-filter-fill iconfont' },
  { value: 'el-icon-scjd-fire iconfont' },
  { value: 'el-icon-scjd-fire-fill iconfont' },
  { value: 'el-icon-scjd-flag iconfont' },
  { value: 'el-icon-scjd-flag1 iconfont' },
  { value: 'el-icon-scjd-flag-Japan iconfont' },
  { value: 'el-icon-scjd-flow iconfont' },
  { value: 'el-icon-scjd-folder-view iconfont' },
  { value: 'el-icon-scjd-font-size iconfont' },
  { value: 'el-icon-scjd-fork iconfont' },
  { value: 'el-icon-scjd-formatpainter iconfont' },
  { value: 'el-icon-scjd-funnel-plot iconfont' },
  { value: 'el-icon-scjd-funnelplot-fill iconfont' },
  { value: 'el-icon-scjd-gold iconfont' },
  { value: 'el-icon-scjd-golden-fill iconfont' },
  { value: 'el-icon-scjd-group iconfont' },
  { value: 'el-icon-scjd-heart iconfont' },
  { value: 'el-icon-scjd-heart-fill iconfont' },
  { value: 'el-icon-scjd-heat-map iconfont' },
  { value: 'el-icon-scjd-highlight iconfont' },
  { value: 'el-icon-scjd-highlight-fill iconfont' },
  { value: 'el-icon-scjd-home iconfont' },
  { value: 'el-icon-scjd-home-fill iconfont' },
  { value: 'el-icon-scjd-hourglass iconfont' },
  { value: 'el-icon-scjd-hourglass-fill iconfont' },
  { value: 'el-icon-scjd-id-card iconfont' },
  { value: 'el-icon-scjd-idcard-fill iconfont' },
  { value: 'el-icon-scjd-index iconfont' },
  { value: 'el-icon-scjd-insurance iconfont' },
  { value: 'el-icon-scjd-insurance-fill iconfont' },
  { value: 'el-icon-scjd-ipad iconfont' },
  { value: 'el-icon-scjd-key iconfont' },
  { value: 'el-icon-scjd-language iconfont' },
  { value: 'el-icon-scjd-language-fill iconfont' },
  { value: 'el-icon-scjd-laptop iconfont' },
  { value: 'el-icon-scjd-layout iconfont' },
  { value: 'el-icon-scjd-layout-fill iconfont' },
  { value: 'el-icon-scjd-like iconfont' },
  { value: 'el-icon-scjd-like-fill iconfont' },
  { value: 'el-icon-scjd-loading iconfont' },
  { value: 'el-icon-scjd-logo-alipay iconfont' },
  { value: 'el-icon-scjd-logo-aliwangwang iconfont' },
  { value: 'el-icon-scjd-logo-aliwangwang-fill iconfont' },
  { value: 'el-icon-scjd-logo-amazon iconfont' },
  { value: 'el-icon-scjd-logo-android iconfont' },
  { value: 'el-icon-scjd-logo-android-fill iconfont' },
  { value: 'el-icon-scjd-logo-ant-cloud iconfont' },
  { value: 'el-icon-scjd-logo-ant-design iconfont' },
  { value: 'el-icon-scjd-logo-apple iconfont' },
  { value: 'el-icon-scjd-logo-apple-fill iconfont' },
  { value: 'el-icon-scjd-logo-applets iconfont' },
  { value: 'el-icon-scjd-logo-dingtalk iconfont' },
  { value: 'el-icon-scjd-logo-facebook iconfont' },
  { value: 'el-icon-scjd-logo-github iconfont' },
  { value: 'el-icon-scjd-logo-gitlab iconfont' },
  { value: 'el-icon-scjd-logo-gitlab-fill iconfont' },
  { value: 'el-icon-scjd-logo-google iconfont' },
  { value: 'el-icon-scjd-logo-google-plus iconfont' },
  { value: 'el-icon-scjd-logo-HTML iconfont' },
  { value: 'el-icon-scjd-logo-IE iconfont' },
  { value: 'el-icon-scjd-logo-instagram iconfont' },
  { value: 'el-icon-scjd-logo-instagram-fill iconfont' },
  { value: 'el-icon-scjd-logo-linkedin iconfont' },
  { value: 'el-icon-scjd-logo-qq iconfont' },
  { value: 'el-icon-scjd-logo-stackflow iconfont' },
  { value: 'el-icon-scjd-logo-taobao iconfont' },
  { value: 'el-icon-scjd-logo-twitter iconfont' },
  { value: 'el-icon-scjd-logo-wechat-fill iconfont' },
  { value: 'el-icon-scjd-logo-weibo iconfont' },
  { value: 'el-icon-scjd-logo-whatsapp iconfont' },
  { value: 'el-icon-scjd-logo-windows iconfont' },
  { value: 'el-icon-scjd-logo-windows-fill iconfont' },
  { value: 'el-icon-scjd-logo-yahoo iconfont' },
  { value: 'el-icon-scjd-logo-Youtube iconfont' },
  { value: 'el-icon-scjd-logo-yuque iconfont' },
  { value: 'el-icon-scjd-logo-zhihu iconfont' },
  { value: 'el-icon-scjd-mail-fill iconfont' },
  { value: 'el-icon-scjd-medal iconfont' },
  { value: 'el-icon-scjd-medal-fill iconfont' },
  { value: 'el-icon-scjd-medicine-box iconfont' },
  { value: 'el-icon-scjd-medicinebox-fill iconfont' },
  { value: 'el-icon-scjd-minus-square iconfont' },
  { value: 'el-icon-scjd-minus-square-fill iconfont' },
  { value: 'el-icon-scjd-mobile iconfont' },
  { value: 'el-icon-scjd-mobile-fill iconfont' },
  { value: 'el-icon-scjd-monitor iconfont' },
  { value: 'el-icon-scjd-notification iconfont' },
  { value: 'el-icon-scjd-notification1 iconfont' },
  { value: 'el-icon-scjd-notification-fill iconfont' },
  { value: 'el-icon-scjd-notification-off iconfont' },
  { value: 'el-icon-scjd-order iconfont' },
  { value: 'el-icon-scjd-order-unread iconfont' },
  { value: 'el-icon-scjd-Partition iconfont' },
  { value: 'el-icon-scjd-phonecall iconfont' },
  { value: 'el-icon-scjd-phonecall-off iconfont' },
  { value: 'el-icon-scjd-play-backward iconfont' },
  { value: 'el-icon-scjd-play-circle-fill iconfont' },
  { value: 'el-icon-scjd-play-fast-backward iconfont' },
  { value: 'el-icon-scjd-play-fast-forward iconfont' },
  { value: 'el-icon-scjd-play-forward iconfont' },
  { value: 'el-icon-scjd-play-pause iconfont' },
  { value: 'el-icon-scjd-play-pause-fill iconfont' },
  { value: 'el-icon-scjd-play-step-backward iconfont' },
  { value: 'el-icon-scjd-play-step-forward iconfont' },
  { value: 'el-icon-scjd-plus-square iconfont' },
  { value: 'el-icon-scjd-plus-square-fill iconfont' },
  { value: 'el-icon-scjd-pointerleft iconfont' },
  { value: 'el-icon-scjd-police iconfont' },
  { value: 'el-icon-scjd-police1 iconfont' },
  { value: 'el-icon-scjd-police2 iconfont' },
  { value: 'el-icon-scjd-police-car iconfont' },
  { value: 'el-icon-scjd-police-clock iconfont' },
  { value: 'el-icon-scjd-policeman iconfont' },
  { value: 'el-icon-scjd-police-message iconfont' },
  { value: 'el-icon-scjd-printer-fill iconfont' },
  { value: 'el-icon-scjd-project iconfont' },
  { value: 'el-icon-scjd-project-fill iconfont' },
  { value: 'el-icon-scjd-pushpin iconfont' },
  { value: 'el-icon-scjd-pushpin-fill iconfont' },
  { value: 'el-icon-scjd-reconciliation iconfont' },
  { value: 'el-icon-scjd-reconciliation-fill iconfont' },
  { value: 'el-icon-scjd-reddit iconfont' },
  { value: 'el-icon-scjd-renew iconfont' },
  { value: 'el-icon-scjd-Report iconfont' },
  { value: 'el-icon-scjd-robot iconfont' },
  { value: 'el-icon-scjd-robot-fill iconfont' },
  { value: 'el-icon-scjd-rocket iconfont' },
  { value: 'el-icon-scjd-rocket-fill iconfont' },
  { value: 'el-icon-scjd-safetycertificate iconfont' },
  { value: 'el-icon-scjd-safetycertificate-f iconfont' },
  { value: 'el-icon-scjd-sand-box iconfont' },
  { value: 'el-icon-scjd-save iconfont' },
  { value: 'el-icon-scjd-save-fill iconfont' },
  { value: 'el-icon-scjd-scan iconfont' },
  { value: 'el-icon-scjd-scissor iconfont' },
  { value: 'el-icon-scjd-search iconfont' },
  { value: 'el-icon-scjd-securityscan iconfont' },
  { value: 'el-icon-scjd-securityscan-fill iconfont' },
  { value: 'el-icon-scjd-send iconfont' },
  { value: 'el-icon-scjd-sever iconfont' },
  { value: 'el-icon-scjd-sever-fill iconfont' },
  { value: 'el-icon-scjd-shake iconfont' },
  { value: 'el-icon-scjd-shop iconfont' },
  { value: 'el-icon-scjd-shop-fill iconfont' },
  { value: 'el-icon-scjd-shortcut iconfont' },
  { value: 'el-icon-scjd-signal-fill iconfont' },
  { value: 'el-icon-scjd-singal iconfont' },
  { value: 'el-icon-scjd-skin iconfont' },
  { value: 'el-icon-scjd-skin-fill iconfont' },
  { value: 'el-icon-scjd-sliders iconfont' },
  { value: 'el-icon-scjd-sliders-fill iconfont' },
  { value: 'el-icon-scjd-small-dash iconfont' },
  { value: 'el-icon-scjd-snippets iconfont' },
  { value: 'el-icon-scjd-snippets-fill iconfont' },
  { value: 'el-icon-scjd-solution iconfont' },
  { value: 'el-icon-scjd-sort-ascending iconfont' },
  { value: 'el-icon-scjd-sort-descending iconfont' },
  { value: 'el-icon-scjd-sound iconfont' },
  { value: 'el-icon-scjd-sound-fill iconfont' },
  { value: 'el-icon-scjd-Storedprocedure iconfont' },
  { value: 'el-icon-scjd-strikethrough iconfont' },
  { value: 'el-icon-scjd-table iconfont' },
  { value: 'el-icon-scjd-tablet iconfont' },
  { value: 'el-icon-scjd-tablet-fill iconfont' },
  { value: 'el-icon-scjd-tag iconfont' },
  { value: 'el-icon-scjd-tag-fill iconfont' },
  { value: 'el-icon-scjd-tags iconfont' },
  { value: 'el-icon-scjd-tags-fill iconfont' },
  { value: 'el-icon-scjd-thunderbolt iconfont' },
  { value: 'el-icon-scjd-thunderbolt-fill iconfont' },
  { value: 'el-icon-scjd-tool iconfont' },
  { value: 'el-icon-scjd-tool-fill iconfont' },
  { value: 'el-icon-scjd-translate iconfont' },
  { value: 'el-icon-scjd-ungroup iconfont' },
  { value: 'el-icon-scjd-unlike iconfont' },
  { value: 'el-icon-scjd-unlike-fill iconfont' },
  { value: 'el-icon-scjd-unlock iconfont' },
  { value: 'el-icon-scjd-unlock-fill iconfont' },
  { value: 'el-icon-scjd-USB iconfont' },
  { value: 'el-icon-scjd-USB-fill iconfont' },
  { value: 'el-icon-scjd-user iconfont' },
  { value: 'el-icon-scjd-useradd iconfont' },
  { value: 'el-icon-scjd-user-bussiness-man iconfont' },
  { value: 'el-icon-scjd-user-delete iconfont' },
  { value: 'el-icon-scjd-user-partner iconfont' },
  { value: 'el-icon-scjd-user-sub-account iconfont' },
  { value: 'el-icon-scjd-user-switch iconfont' },
  { value: 'el-icon-scjd-user-team iconfont' },
  { value: 'el-icon-scjd-user-teamadd iconfont' },
  { value: 'el-icon-scjd-user-team-delete iconfont' },
  { value: 'el-icon-scjd-verified iconfont' },
  { value: 'el-icon-scjd-videoadd iconfont' },
  { value: 'el-icon-scjd-video-fill iconfont' },
  { value: 'el-icon-scjd-View iconfont' },
  { value: 'el-icon-scjd-vip iconfont' },
  { value: 'el-icon-scjd-vip-fill iconfont' },
  { value: 'el-icon-scjd-warehouse iconfont' },
  { value: 'el-icon-scjd-wifi iconfont' }
]
